import Foundation

/// Production `QuorumCoreBridge` backed by the Rust core through UniFFI.
///
/// The generated bindings (`quorumDraftFieldSignal`, `FfiQuorumSignalDraft`,
/// `QuorumError`, …) live in `CoreBridge/QuorumFFI.swift` and link against
/// `CoreBridge/QuorumFFI.xcframework`. Both are regenerated by
/// `scripts/build-mobile-ffi-ios.sh` and are gitignored, so this file does not
/// compile until that script has produced them.
///
/// This adapter is the *only* place the FFI wire DTOs (`Ffi*`, string-typed)
/// are translated to and from the Swift domain types — mirroring the boundary
/// mapping the Rust side performs in `quorum-ffi/src/lib.rs`.
public struct QuorumCoreBridgeFFI: QuorumCoreBridge {
    public init() {}

    public func workflowId() async -> String {
        quorumFieldSignalWorkflowId()
    }

    public func draftFieldSignal(
        inquiryThreadId: String,
        modality: SignalModality,
        rawCapture: String
    ) async throws -> FieldSignalDraft {
        let draft = try quorumDraftFieldSignal(
            inquiryThreadId: inquiryThreadId,
            modality: modality.rawValue,
            rawCapture: rawCapture
        )
        return try Self.domainDraft(draft)
    }

    public func appendConsentedSignal(_ draft: FieldSignalDraft) async throws -> QuorumAppendEvent {
        let event = try quorumAppendConsentedSignal(draft: Self.ffiDraft(draft))
        return QuorumAppendEvent(
            workflowId: event.workflowId,
            eventType: event.eventType,
            draftId: event.draftId,
            inquiryThreadId: event.inquiryThreadId,
            syncState: event.syncState
        )
    }

    // MARK: - Boundary mapping (FFI wire DTO <-> Swift domain)

    private static func domainDraft(_ ffi: FfiQuorumSignalDraft) throws -> FieldSignalDraft {
        guard let modality = SignalModality(rawValue: ffi.modality) else {
            throw QuorumError.InvalidModality(value: ffi.modality)
        }
        return FieldSignalDraft(
            workflowId: ffi.workflowId,
            draftId: ffi.draftId,
            inquiryThreadId: ffi.inquiryThreadId,
            modality: modality,
            rawCapture: ffi.rawCapture,
            summary: ffi.summary,
            latentNeed: ffi.latentNeed,
            contradiction: ffi.contradiction,
            confidence: ffi.confidence,
            consentState: ffi.consentState
        )
    }

    private static func ffiDraft(_ draft: FieldSignalDraft) -> FfiQuorumSignalDraft {
        FfiQuorumSignalDraft(
            workflowId: draft.workflowId,
            draftId: draft.draftId,
            inquiryThreadId: draft.inquiryThreadId,
            modality: draft.modality.rawValue,
            rawCapture: draft.rawCapture,
            summary: draft.summary,
            latentNeed: draft.latentNeed,
            contradiction: draft.contradiction,
            confidence: draft.confidence,
            consentState: draft.consentState
        )
    }
}
