import Foundation

/// Raised when the Rust core returns a value this app build cannot map into a
/// domain type. With modality/consent/event/sync now enums on the wire, the only
/// remaining unmappable value is a confidence outside `0...1` (a float the UDL
/// can't constrain). Distinct from the generated `QuorumError`, which the FFI
/// functions themselves throw when the *core* rejects input.
public enum CoreBridgeError: Error {
    case confidenceOutOfRange(Float)
}

/// Production `QuorumCoreBridge` backed by the Rust core through UniFFI.
///
/// The generated bindings (`quorumDraftFieldSignal`, `FfiQuorumSignalDraft`,
/// `QuorumError`, …) live in `CoreBridge/QuorumFFI.swift` and link against
/// `CoreBridge/QuorumFFI.xcframework`. Both are regenerated by
/// `scripts/build-mobile-ffi-ios.sh` and are gitignored, so this file does not
/// compile until that script has produced them.
///
/// This adapter is the *only* place the FFI wire DTOs (`Ffi*`) are translated to
/// and from the Swift domain types — mirroring the boundary mapping the Rust side
/// performs in `quorum-ffi/src/lib.rs`. The closed-set fields are enums on the
/// wire now, so they cross unchanged; only `confidence` (a float) is validated.
///
/// It is an `actor` so the synchronous FFI calls run on the actor's executor,
/// off the main thread (ADR 0003): a `@MainActor` view `await`s these methods,
/// the Rust work happens off-main, and the `Sendable` result returns to the
/// main actor — the UI is never blocked. This matches the Android bridge, which
/// runs the same FFI on `Dispatchers.Default`.
public actor QuorumCoreBridgeFFI: QuorumCoreBridge {
    private let queuePersistence: QuorumQueuePersistence

    public init(queuePersistence: QuorumQueuePersistence? = nil) throws {
        if let queuePersistence {
            self.queuePersistence = queuePersistence
        } else {
            self.queuePersistence = try QuorumQueuePersistence.production()
        }
    }

    public func workflowId() async -> String {
        quorumFieldSignalWorkflowId()
    }

    public func currentDirectorSnapshot() async throws -> DirectorSnapshot {
        let snapshot = quorumCurrentDirectorSnapshot()
        return DirectorBridgeMapping.domainSnapshot(snapshot)
    }

    public func directorSnapshotSource() async -> String {
        quorumDirectorSnapshotSource()
    }

    public func submitDirectorIntent(_ intent: DirectorIntent) async throws {
        quorumSubmitDirectorIntent(intent: DirectorBridgeMapping.ffiIntent(intent))
    }

    public func draftFieldSignal(
        inquiryThreadId: String,
        modality: SignalModality,
        rawCapture: String
    ) async throws -> FieldSignalDraft {
        let draft = quorumDraftFieldSignal(
            inquiryThreadId: inquiryThreadId,
            modality: modality,
            rawCapture: rawCapture
        )
        return try Self.domainDraft(draft)
    }

    public func appendConsentedSignal(_ draft: FieldSignalDraft) async throws -> QuorumAppendEvent {
        let event = try quorumAppendConsentedSignal(draft: Self.ffiDraft(draft))
        return Self.domainEvent(event)
    }

    public func persistConsentedSignalToQueue(_ draft: FieldSignalDraft) async throws -> PersistedQueueRecordSummary {
        try queuePersistence.persistConsentedSignal(draft)
    }

    public func loadPersistedQueueRecords() async throws -> [PersistedQueueRecordSummary] {
        try queuePersistence.loadPersistedRecords()
    }

    // MARK: - Boundary mapping (FFI wire DTO <-> Swift domain)
    // The single place wire strings/floats become domain types and back,
    // mirroring the Rust boundary in quorum-ffi/src/lib.rs.

    private static func domainDraft(_ ffi: FfiQuorumSignalDraft) throws -> FieldSignalDraft {
        // modality/consentState are enums on the wire — they cross as-is; only the
        // float confidence still needs range validation the UDL can't express.
        guard let confidence = Confidence(ffi.confidence) else {
            throw CoreBridgeError.confidenceOutOfRange(ffi.confidence)
        }
        return FieldSignalDraft(
            workflowId: ffi.workflowId,
            draftId: ffi.draftId,
            inquiryThreadId: ffi.inquiryThreadId,
            modality: ffi.modality,
            rawCapture: ffi.rawCapture,
            summary: ffi.summary,
            latentNeed: ffi.latentNeed,
            contradiction: ffi.contradiction,
            confidence: confidence,
            consentState: ffi.consentState
        )
    }

    private static func domainEvent(_ ffi: FfiQuorumAppendEvent) -> QuorumAppendEvent {
        // eventType/syncState are enums on the wire — nothing left to validate.
        QuorumAppendEvent(
            workflowId: ffi.workflowId,
            eventType: ffi.eventType,
            draftId: ffi.draftId,
            inquiryThreadId: ffi.inquiryThreadId,
            syncState: ffi.syncState
        )
    }

    private static func ffiDraft(_ draft: FieldSignalDraft) -> FfiQuorumSignalDraft {
        FfiQuorumSignalDraft(
            workflowId: draft.workflowId,
            draftId: draft.draftId,
            inquiryThreadId: draft.inquiryThreadId,
            modality: draft.modality,
            rawCapture: draft.rawCapture,
            summary: draft.summary,
            latentNeed: draft.latentNeed,
            contradiction: draft.contradiction,
            confidence: draft.confidence.value,
            consentState: draft.consentState
        )
    }
}
