import Foundation

/// Raised when the Rust core returns a value this app build cannot map into a
/// domain type (a core/app version skew). Distinct from the generated
/// `QuorumError`, which the FFI functions themselves throw when the *core*
/// rejects input.
public enum CoreBridgeError: Error {
    case unrecognizedCoreValue(field: String, value: String)
    case confidenceOutOfRange(Float)
}

/// Production `QuorumCoreBridge` backed by the Rust core through UniFFI.
///
/// The generated bindings (`quorumDraftFieldSignal`, `FfiQuorumSignalDraft`,
/// `QuorumError`, …) live in `CoreBridge/QuorumFFI.swift` and link against
/// `CoreBridge/QuorumFFI.xcframework`. Both are regenerated by
/// `scripts/build-mobile-ffi-ios.sh` and are gitignored, so this file does not
/// compile until that script has produced them.
///
/// This adapter is the *only* place the FFI wire DTOs (`Ffi*`, string-typed)
/// are translated to and from the Swift domain types — mirroring the boundary
/// mapping the Rust side performs in `quorum-ffi/src/lib.rs`.
public struct QuorumCoreBridgeFFI: QuorumCoreBridge {
    public init() {}

    public func workflowId() async -> String {
        quorumFieldSignalWorkflowId()
    }

    public func draftFieldSignal(
        inquiryThreadId: String,
        modality: SignalModality,
        rawCapture: String
    ) async throws -> FieldSignalDraft {
        let draft = try quorumDraftFieldSignal(
            inquiryThreadId: inquiryThreadId,
            modality: modality.rawValue,
            rawCapture: rawCapture
        )
        return try Self.domainDraft(draft)
    }

    public func appendConsentedSignal(_ draft: FieldSignalDraft) async throws -> QuorumAppendEvent {
        let event = try quorumAppendConsentedSignal(draft: Self.ffiDraft(draft))
        return try Self.domainEvent(event)
    }

    // MARK: - Boundary mapping (FFI wire DTO <-> Swift domain)
    // The single place wire strings/floats become domain types and back,
    // mirroring the Rust boundary in quorum-ffi/src/lib.rs.

    private static func domainDraft(_ ffi: FfiQuorumSignalDraft) throws -> FieldSignalDraft {
        guard let modality = SignalModality(rawValue: ffi.modality) else {
            throw CoreBridgeError.unrecognizedCoreValue(field: "modality", value: ffi.modality)
        }
        guard let consentState = ConsentState(rawValue: ffi.consentState) else {
            throw CoreBridgeError.unrecognizedCoreValue(
                field: "consentState", value: ffi.consentState
            )
        }
        guard let confidence = Confidence(ffi.confidence) else {
            throw CoreBridgeError.confidenceOutOfRange(ffi.confidence)
        }
        return FieldSignalDraft(
            workflowId: ffi.workflowId,
            draftId: ffi.draftId,
            inquiryThreadId: ffi.inquiryThreadId,
            modality: modality,
            rawCapture: ffi.rawCapture,
            summary: ffi.summary,
            latentNeed: ffi.latentNeed,
            contradiction: ffi.contradiction,
            confidence: confidence,
            consentState: consentState
        )
    }

    private static func domainEvent(_ ffi: FfiQuorumAppendEvent) throws -> QuorumAppendEvent {
        guard let eventType = AppendEventType(rawValue: ffi.eventType) else {
            throw CoreBridgeError.unrecognizedCoreValue(field: "eventType", value: ffi.eventType)
        }
        guard let syncState = SyncState(rawValue: ffi.syncState) else {
            throw CoreBridgeError.unrecognizedCoreValue(field: "syncState", value: ffi.syncState)
        }
        return QuorumAppendEvent(
            workflowId: ffi.workflowId,
            eventType: eventType,
            draftId: ffi.draftId,
            inquiryThreadId: ffi.inquiryThreadId,
            syncState: syncState
        )
    }

    private static func ffiDraft(_ draft: FieldSignalDraft) -> FfiQuorumSignalDraft {
        FfiQuorumSignalDraft(
            workflowId: draft.workflowId,
            draftId: draft.draftId,
            inquiryThreadId: draft.inquiryThreadId,
            modality: draft.modality.rawValue,
            rawCapture: draft.rawCapture,
            summary: draft.summary,
            latentNeed: draft.latentNeed,
            contradiction: draft.contradiction,
            confidence: draft.confidence.value,
            consentState: draft.consentState.rawValue
        )
    }
}
